alltoys/alltoys/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(("toys.urls","toys"))),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

alltoys/toys/urls.py
from django.urls import path
from . import views

app_name = "toys"
urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('toys/', views.show_toys, name="show_toys"),
    path('users/', views.show_users, name="show_users"),
]

alltoys/company/models.py
from django.db import models


class ActiveobjectsMaмук(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class Company(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()



class Employee(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField()
    destination = models.CharField(max_length=50)
    salary = models.DecimalField(max_digits=10,decimal_places=2)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="employees")
    description = models.TextField()

alltoys/toys/models.py
from django.db import models


class ActiveobjectsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class Address(models.Model):
    address = models.CharField(max_length=100)
    country = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.CharField(max_length=100, null=True, blank=True)


class User(models.Model):
    is_active = models.BooleanField(default=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField()
    address = models.OneToOneField(Address, on_delete=models.PROTECT,null=True,blank=True)

    objects = models.Manager()

    active_objects = ActiveobjectsManager()


class Tag(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)


class Toy(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, related_name="toys", on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag, related_name="toys")

alltoys/company/views.py
from django.shortcuts import render

# Create your views here.

alltoys/toys/views.py
from django.shortcuts import render

from toys.models import User, Toy


def show_users(request):
    users = User.objects.all()
    return render(request, 'toys/show_users.html', context={"users": users})


def dashboard(request):
    return render(request, "toys/dashboard.html", context={"Welcome_text": "Welcome to all_toys,  fazliddinkomilov"})


def show_toys(request):
    toys = Toy.objects.all()
    return render(request, 'toys/show_users.html', context={"toys": toys})

alltoys/toys/templates/toys/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    {{Welcome_text}}
</div>
<div>
    <table>
        <tr>
            <td style="width: 100px"><a href="{% url "toys:show_toys" %}">Toys</a></td>
            <td style="width: 100px"><a href="{% url "toys:show_users" %}">Users</a></td>
        </tr>
    </table>
</div>

</body>
</html>

alltoys/toys/templates/toys/show_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3>Toys</h3>
{% for toy in toys %}
    <p>{{toy.name}}</p>
{% endfor %}

<h3>Users</h3>
{% for user in users %}
    <p>{{user.first_name}} {{user.last_name}}</p>
{% endfor %}

</body>
<html>